### ISSUE TITLE
Version 1.2 regresses oauth dependency

### ISSUE THREAD

**Issue by indirect** [instructure/ims-lti#115]
In version 1.1.13, the `oauth` dependency was relaxed to `> 0.4.5, < 0.6`. However, in commit 6a91689b16894d2b20650002f7c8e33c3d47a1f4, @rivernate overwrote that change and restored a hard dependency on exactly oauth 0.4.5, and that regression was released in ims-lti 1.2.

**Comment by rivernate** [comment]
this was fixed in #120
