### ISSUE TITLE
How do I manage outcomes?

### ISSUE THREAD

**Issue by jodydeanrogan** [instructure/ims-lti#126]
First of all, thanks for this gem.  So far, I have successfully used this gem to launch a tool from a tool provider and to create user accounts and/or login in users at the same time.

The problem I'm having is that I can't figure out how to manage outcomes, I'd like to be able to make a request for the grades of a specific student, I'm not sure how to go about this.

Any help would be much appreciated.

**Comment by SoxFace** [comment]
Hi Jody, 

Atomic Jolt helped me understand outcomes. Justin Ball starts coding the outcomes in their LTI Starter App @1:13 https://youtu.be/pPw8VD4iQkI?list=PLUAEXpf1UDMnKtzMVzuh-aYjss1MlcpCF

Good Luck!

**Comment by rivernate** [comment]
The 2.x version of the gem doesn't support outcomes yet.  For now you would need to go back to the 1.x version of the gem, or implement it separately.
