### ISSUE TITLE
LTI Launch fails for content item selection with latest IMS-LTI gem

### ISSUE THREAD

**Issue by jbasdf** [instructure/ims-lti#128]
The IMS::LTI::Services::MessageAuthenticator initialization parses the params object into options and parsed_params.

The course level navigation results in an @options that looks like this:

{:consumer_key=>"lti-example-dev", :signature_method=>"HMAC-SHA1", :timestamp=>"1498094063", :nonce=>"sTtZphI5tfJarJfZQksP1Bdm6nILujuMntjpVk10bc", :version=>"1.0", :callback=>"about:blank"}

 The content item selection results in an @options that looks like this:

{:consumer_key=>"lti-example-dev", :signature_method=>"HMAC-SHA1", :timestamp=>"1498094088", :nonce=>"TTNKN94qqjX8vmehAIlsod7GhXLkQpRqy52FxYamG4", :version=>"1.0"}

The primary difference is that the content item selection does not have a callback.

In message_authenticator.rb there's this bit of code that generates the simple_oauth_header. By default it always adds in a callback even if the request doesn't include that value. If I remove the callback then the signature succeeds. Is there a reason to always have a default callback value?

 `def simple_oauth_header
  @simple_oauth_header ||= begin
    @simple_oauth_header = SimpleOAuth::Header.new(
      :post, launch_url,
      @parsed_params,
      @options.merge(
        {
          consumer_key: consumer_key,
          consumer_secret: @secret,
          callback: 'about:blank'
        }
      )
    )
    @simple_oauth_header
  end
end`

I also discussed this issue in the Canvas community. For reference, here's a link:
https://community.canvaslms.com/message/72970-lti-launch-fails-for-content-item-selection-with-latest-ims-lti-gem

**Comment by rivernate** [comment]
This is fixed in: #125
