### ISSUE TITLE
ToolProxyRegistrationService.tool_consumer profile request does not set correct headers or `lti_version`

### ISSUE THREAD

**Issue by DoubtedGoat** [instructure/ims-lti#139]
The `GET` request issued to fetch the tool consumer profile does not set the correct Accept header of `application/vnd.ims.lti.v2.toolconsumerprofile+json`, and does not add the `lti_version` parameter to the request. 
Both of these requirements are specified here
https://www.imsglobal.org/lti/model/uml/purl.imsglobal.org/vocab/lti/v2/lti/ToolConsumerProfile/service.html
in section 3.1. Attempting the request without either results in a 400 error when running the IMS LTI certification test suite.

**Comment by rivernate** [comment]
[IMS is transitioning LTI 2.0 to legacy status starting January 2018](https://www.imsglobal.org/lti-adoption-roadmap). Because of this, we are not going to be doing any more work on LTI 2.x for this gem.
