### ISSUE TITLE
LoadError in Controller#index / Cannot load such file -> ims/lit

### ISSUE THREAD

**Issue by MarkKing** [instructure/ims-lti#14]
Hi Guys,

I'm developing in a Rails 4.0 / Ruby 2 environment - and encountered s the above issue when using the following 'require' statement in my consumer code (as per your wiki guidance):

require 'ims/lit'

To resolve this issue, I modified the require statement to

require 'ims'

This is just a heads up more than anything... maybe adding a note to the wiki page might be useful. Many thanks for developing this gem, really helped fastrack my LTI implementation knowledge.

Mark

**Comment by rivernate** [comment]
the documentation should now reflect the correct require statement
