### ISSUE TITLE
Trying to build a tool provider that uses content-item message –– wondering if this library could be used

### ISSUE THREAD

**Issue by gordonbisnor** [instructure/ims-lti#140]
We're attempting to build a product for the various LMS services and hoping to us Content-Item Message  –– at the moment I have a launch to a Rails application working, and am trying to find information on how to successfully POST back to the LMS either server-side or via javascript-triggered form submission –– have ben unable to find documentation that has enabled me to get this working. From some issues I've seen posted here, it looks like this library could potentially handle this, but not sure yet.

**Comment by gordonbisnor** [comment]
I've subsequently been reading through code and have had initial success with  IMS::LTI::Models::Messages::ContentItemSelection and  IMS::LTI::Models::ContentItems.xx:

```ruby
    message = IMS::LTI::Models::Messages::ContentItemSelection.new(body)
    
    content_item = IMS::LTI::Models::ContentItems::LtiLinkItem.new({
      title: "Hello there",
      text: "Some lorem ipsem here",
      url: "http://www.something.com",
      media_type: 'text/html',
      type: "ContentItem"
    })

    message.content_items = [content_item]

    #
    # Server-side POST with Httparty
    # 
    result = self.class.post(return_url, {
      headers: {}, 
      body: message.signed_post_params('secret')
    })
```

I'm assuming that maybe this is not the intended/ideal usage though –– will look at putting those signed post params into a form and submitting via javascript, etc.

**Comment by gordonbisnor** [comment]
Have tried again without doing a server-side POST, instead capturing the result of  

```ruby
message.signed_post_params('secret')
``

and then iterating through that array to get input names and values, and then submitting, sems to work...

<form  encType="application/x-www-form-urlencoded" method="post" action="<%= @return_url %>" id="assignment_selection">
  <% @form_elements.each do |element| %>
    <input name="<%= element[0] %>" value="<%= element[1] %>" />
  <% end -%>
</form>
<script>
   document.getElementById('assignment_selection').submit();
</script>

**Comment by rivernate** [comment]
It looks like you have gotten it working. The idea of the gem is to not do the launch itself, but to create the signed form parameters you can use to make the post using the user agent.
