### ISSUE TITLE
LTI Advantage support

### ISSUE THREAD

**Issue by octavpo** [instructure/ims-lti#145]
IMS has recently announced that it's abandoning LTI 2.0 in favor of a new concept called LTI Advantage, which seems to be including LTI 1.1 + several extensions. So then I'm wondering what version of this gem is compatible with that. Should we still be using version 2 or should we go back to version 1? How is it going to evolve from here? Thanks.

**Comment by rivernate** [comment]
The current version currently supports lti 1.1, and it's what I would suggest you use. It also has some support for membership services, now known as Names and Role Provisioning Services.  The Assignment and Grade Services specification hasn't been released yet, and doesn't have any support in this library currently.
