### ISSUE TITLE
Question: Does this gem support LTI v1.3?

### ISSUE THREAD

**Issue by saulcosta** [instructure/ims-lti#158]
I know it supports 1.1 and 1.2, but is 1.3 supported?

**Comment by derigible** [comment]
@saulcosta no, this gem does not support LTI 1.3. We have no immediate plans to add support at this time either.

**Comment by saulcosta** [comment]
Okay, thanks for the info and fast response.

**Comment by rlorenzo** [comment]
@derigible I was planning on evaluating RoR as a platform for developing our LTI apps, but I would have to rule them out if there isn't a library to help with LTI 1.3 like PHP (https://github.com/IMSGlobal/lti-1-3-php-library).

This is by far the most popular Ruby Gem for LTI and I don't see any other gems supporting LTI 1.3.

What are the reasons for not supporting LTI 1.3?

**Comment by westonkd** [comment]
@rlorenzo :wave: 

The primary reason our team has not added LTI Advantage support is time constraints.

We _do_ have an lti-advantage gem bundle in the canvas-lms repo if it's helpful to you: https://github.com/instructure/canvas-lms/tree/master/gems/lti-advantage/lib/lti_advantage

That gem primarily provides models for the various LTI Advantage messages, so it may not be exactly what you are looking for.

If we get time, we'd certainly love to expand that gem to be more useful for tool providers and extract it to it's own project. If/when that happens we will update this project's readme with a link to the new repository.
