### ISSUE TITLE
Are there any documentation regarding versions 2.x.x? (which uses OAuth)

### ISSUE THREAD

**Issue by jeniaefimov** [instructure/ims-lti#173]
Hi, thanks for the great gem.

We're on our way to upgrading LTI to version 1.3 and would like to use your gem (at least partially). Do you have any documentation regarding versions 2. x.x?

I really appreciate any help you can provide.

**Comment by Ardena** [comment]
LTI 2.x.x was in between 1.1 and 1.3, but it was a failed version.  The versioning number is weird because IMS decided to go back to something more similar to 1.1.  But LTI 2.x.x is completely deprecated.

**Comment by jeniaefimov** [comment]
@Ardena thanks for the answer, maybe there is some documentation about using this gem for version 1.3 (with Oauth2, etc.)?

**Comment by dumbledad** [comment]
@Ardena I'm confused, https://rubygems.org/gems/ims-lti/ states that 2.3.2 is the most recent version?

**Comment by xandroxygen** [comment]
I left some context in this comment https://github.com/instructure/ims-lti/issues/175#issuecomment-1289410157, but Ardena was talking about the _LTI_ versions, not the versions of this gem. She is correct in that  LTI 2 is deprecated, and that v2 of this gem is built for that deprecated LTI 2 standard.

@jeniaefimov this gem sadly does not support LTI 1.3 at all.
