### ISSUE TITLE
1.2.4 to 2.2.3, what replicates the ToolConsumer functionality

### ISSUE THREAD

**Issue by dumbledad** [instructure/ims-lti#175]
I need to upgrade an app from v1.2.4 to v2.2.3 (as we are bumping Ruby from v2.7.2 to v3.1.2)

We have simple code which uses `IMS::LTI::ToolConsumer.new`, `IMS::LTI::ToolConsumer.launch_url`, and `IMS::LTI::ToolConsumer.generate_launch_data`. I cannot find and hents on how to change this code to use the new available classes (since `IMS::LTI::ToolConsumer` has now been deleted).

**Comment by xandroxygen** [comment]
Are you running into trouble using the v1.2.x releases with ruby 3? 

There is some context around the large differences between v1 and v2 of this gem. v1 supports LTI 1.1, the original LTI standard. v2 is almost a different gem, and changes many of the classes and functionality provided so that it supports LTI 2.0, which was the successor to LTI 1.1 but was quickly deprecated since it was confusing and also changed the major version instead of using 1.2. Later on, the current version of the LTI standard (1.3) was released, which this gem does not support at all.

All that to say, you should not attempt to upgrade from v1 to v2 because as you noticed, the classes you expect are gone. If there are errors you are experiencing with v1 and ruby 3, you can attach them here!

**Comment by dumbledad** [comment]
@xandroxygen I ended up swapping to the new stuff, but the error I was seeing when swapping from Ruby v2.7.2 to v3.1.2 was this
```
LoadError: cannot load such file -- rexml/document
/tmp/build_be3f223d/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/tmp/build_be3f223d/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
/tmp/build_be3f223d/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/tmp/build_be3f223d/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
/tmp/build_be3f223d/vendor/bundle/ruby/3.1.0/gems/ims-lti-1.2.4/lib/ims/lti.rb:3:in `<main>'
[…]
Caused by:
LoadError: cannot load such file -- ims-lti
```

**Comment by dumbledad** [comment]
And @xandroxygen, this is how I changed the code …

In the controller
```
    def show
      @consumer = IMS::LTI::ToolConsumer.new(
        ENV['FL_LTI_CONSUMER_KEY'],
        ENV['FL_LTI_CONSUMER_SECRET'],
        'launch_url' => ENV['FL_LTI_URL']
      )


      @consumer.custom_params = {
        fl_course_uuid: params[:fl_id],
        fl_external_learner_id: current_user.id
      }
      @consumer.lis_person_sourcedid = current_user.id
      @consumer.lti_message_type = 'basic-lti-launch-request'
      @consumer.lti_version = 'LTI-1p0'
      @consumer.resource_link_id = ''
      render :show, layout: false
    end
  end
```
_becomes_
```
    def show
      @message_authenticator = IMS::LTI::Services::MessageAuthenticator.new(
        ENV.fetch('FL_LTI_URL'),
        {
          consumer_key: ENV.fetch('FL_LTI_CONSUMER_KEY'),
          lis_person_sourcedid: current_user.id,
          lti_message_type: 'basic-lti-launch-request',
          lti_version: 'LTI-1p0',
          resource_link_id: '',
          custom_fl_course_uuid: params[:fl_id],
          custom_fl_external_learner_id: current_user.id
        },
        ENV.fetch('FL_LTI_CONSUMER_SECRET')
      )
      render :show, layout: false
    end
  end
```
and in the erb file
```
<form action="<%= @consumer.launch_url %>" name="ltiLaunchForm" id="ltiLaunchForm" method="post" encType="application/x-www-form-urlencoded">
  <% @consumer.generate_launch_data.each_pair do |key, val| %>
    <input type="hidden" name="<%= key %>" value="<%= val %>"/>
  <% end %>
</form>
```
_becomes_
```
<form action="<%= @message_authenticator.launch_url %>" name="ltiLaunchForm" id="ltiLaunchForm" method="post" encType="application/x-www-form-urlencoded">
  <% @message_authenticator.signed_params.each_pair do |key, val| %>
    <input type="hidden" name="<%= key %>" value="<%= val %>"/>
  <% end %>
</form>
```
I know you say
> you should not attempt to upgrade from v1 to v2 because as you noticed, the classes you expect are gone
But the above 'upgrade' seems to work.

**Comment by xandroxygen** [comment]
oh nice, if it works it works! I'm not very familiar with v2 of this gem so I can't say for sure but if it's working for you then that sounds great. Thanks for posting that, I'm sure it will be helpful for future readers as well. When canvas and its satellite libraries move to ruby 3, I think we will probably revisit this for v1.
