### ISSUE TITLE
generate_request_xml

### ISSUE THREAD

**Issue by octavpo** [instructure/ims-lti#49]
The OutcomeRequest#generate_request_xml method is very useful as a communication debugging tool, it would be great if it were made public, so I don't have to edit the source when I need it. The similar OutcomeResponse#generate_response_xml is already public.

And both of them should accept options, so I can pass an indent to the builder. So something like this:

```
def generate_request_xml options = {}
  builder = Builder::XmlMarkup.new(options)
```

Thanks,
Octav

**Comment by jasonblanchard** [comment]
@octavpo Just submitted #88 which partially addresses this. Let me know if you have any feedback!
