### ISSUE TITLE
bug in generate_identifier in version 1.1.7

### ISSUE THREAD

**Issue by octavpo** [instructure/ims-lti#50]
Method IMS::LTI::generate_identifier tries to generate a unique identifier by calling UUID.new. When that's inserted in a message this it to_s on the UUID object, which generates an internal representation, not the identifier string. The code needs to call UUID.new.generate to get the actual string.

I see this has been changed in version 1.1.8 to use SecureRandom.uuid instead, which I think is a good move, but that is only available in ruby 1.9. So maybe it's worth fixing version 1.1.7 for people still using ruby 1.8.

Thanks,
Octav

**Comment by rivernate** [comment]
we have dropped support for ruby versions less than 2.1. Closing this since it's fixed in newer versions of the gem
