### ISSUE TITLE
Does current implementation support LTI v1.2?

### ISSUE THREAD

**Issue by ppazos** [instructure/ims-lti#62]
If not, is there any plans of releasing a v1.2 update?

Thanks!

**Comment by bracken** [comment]
Is there a specific thing in 1.2 you need. The main thing added in 1.2 is
tool profiles, which this library doesn't support yet.
For most practical purposes there won't be anything extra you need for 1.2.

That said, I don't know of any plans to add 1.2 profiles. Someone probably
will at some point, but most people won't need it.

**Comment by ppazos** [comment]
Thanks for the quick response!

We have a client that is an LMS provider and asked us to implement v1.2. We're investigating possible tools to use and the versions supported. Also, understanding the differences between versions.

Can you point me to any resource that describe those differences between 1.1 and 1.2 in more depth? With that info we can guide the our client better.

Thanks a lot.

**Comment by bracken** [comment]
The specification page for 1.2 list the changes between the versions:

http://www.imsglobal.org/specs/ltiv1p2

It's likely that whatever you're doing, if you're 1.1 compliant, you're also 1.2 compliant. There isn't anything different sent at launch time.

**Comment by bracken** [comment]
I just went through the LTI certification to help test the new suite. The only thing you need to be able to do different for 1.2 is request a Tool Consumer Profile. So, if you have a use for that, go ahead and do it, but it's probably not useful for you.

**Comment by rivernate** [comment]
I'm going to close this since, feel free to reopen it if you still have questions
