### ISSUE TITLE
Port number in launch URL causes tool consumer to produce bad request 

### ISSUE THREAD

**Issue by krozett** [instructure/ims-lti#67]
I spent days debugging an issue where I was using both a ToolProvider and ToolConsumer in an integration test. I was running a local Rails server on the default port (3000) and it turned out that validation would always fail when the port number was included in the launch_url which I used to build the ToolConsumer's request.

Here's a simplified version of my code:
```ruby
tool_consumer = IMS::LTI::ToolConsumer.new(
  "testkey",
  "deep dark secret",
  { "resource_link_id" => 1234, "launch_url" => "http://localhost:3000/auth" }
)
post "http://localhost:3000/auth", tool_consumer.generate_launch_data
```

And in the auth controller:
```ruby
tool_provider = IMS::LTI::ToolProvider.new("testkey", "deep dark secret", params)
tool_provider.valid_request!(request)
```

This would always throw an `OAuth::Unauthorized` exception. If I took out the port in the launch_url it authenticated just fine.

According to this part of the OAuth spec (http://oauth.net/core/1.0/#sig_url), the port and query string should always be removed from the launch url. I believe this is why the validation fails - the RequestValidator module calls `OAuth::Signature.build()` and `verify()` directly, and that module appears to be following the spec by dropping the port from the request digest. It looks like `generate_launch_data` is already dropping the query string, and drops the port if it's the default one. What it should be doing is dropping the port in all cases.

What's the next step? Assuming you guys agree this is a bug, I can provide a pull request that fixes it as well as some tests to verify correctness.

**Comment by rivernate** [comment]
Looking at the spec it looks like it is behaving correctly where it only drops the port if it's the default port:

> Unless specified, URL scheme and authority **MUST be lowercase and include the port number**; http default port 80 and https default port 443 MUST be excluded.

I'm not sure why you are seeing problems with verifying the launch, the launch URL you set in the ToolConsumer class should match exactly what you have in your html form method attribute.

You might also try launching to another tool from your tool consumer code and see what happens.  You can user this test tool to see what happens: http://lti-tool-provider-example.herokuapp.com/

**Comment by krozett** [comment]
It's possible that I'm doing something wrong here, but why would it succeed without the port number and fail with it?

**Comment by krozett** [comment]
Welp, turns out you were right, @rivernate! I put together a simple form and form handler, and the request works as expected. However, I am still getting errors when I use the Rails testing environment, so something is eating the port number. I'm going to see if this is still an issue with recent Rails versions (I'm on 3.1) and submit a bug report to them if it still is.

Maybe if someone else has an issue with Rails integration testing they will stumble across this.

**Comment by rivernate** [comment]
it's an interesting problem, I'm glad you got it narrowed down to the test environment, and hope you can solve it.

**Comment by ayan-biswas0412** [comment]
@krozett did you implemented the tests in spec successfully ? can you give me the repo link of yours I am actually facing similar issues
