### ISSUE TITLE
Support for role_scope_mentor?

### ISSUE THREAD

**Issue by kbighorse** [instructure/ims-lti#8]
Now required for v1.1.1 certification. Happy to contribute a patch if someone can direct me to the relevant part of the code.

http://www.imsglobal.org/LTI/v1p1p1/ltiIMGv1p1p1.html

http://www.imsglobal.org/developers/alliance/LTI/cert/index.php (see 4.10)

**Comment by rivernate** [comment]
https://github.com/instructure/ims-lti/blob/master/lib/ims/lti/models/messages/basic_lti_launch_request.rb has the attributes for the mentor roles.
