### ISSUE TITLE
Support for UTF-8 parameter encoding?

### ISSUE THREAD

**Issue by kbighorse** [instructure/ims-lti#9]
Again, happy to contribute, I think the params just need to have `.encode('UTF-8')` called on them before sending or something. Just direct me to the relevant part of the code.

http://www.imsglobal.org/developers/alliance/LTI/cert/index.php
2.5: Parameters are encoded using UTF-8

**Comment by rivernate** [comment]
I'm going to close this since it's been quiet, feel free to reopen it if you still have questions.
