### ISSUE TITLE
undefined method `code' for nil:NilClass: LTI integration

### ISSUE THREAD

**Issue by dracorna** [instructure/ims-lti#92]
Hello all. We are working on an LTI Integration with canvas in our rails 3 app. However, we are receiving the error 

`undefined method code' for nil:NilClass`

when calling 

`if provider.valid_request?(request, false)`

We have traced this error to the oauth gem, however can not determine why the request is being passed as nil. It is populating when we debug it through logger or a raise and we can not tell if it is getting lost in our handoff to the lti gem or the gem's hand off to oauth. 

Does anyone know anything about this?

**Comment by rivernate** [comment]
I'm going to close this since it's been quiet, feel free to reopen it if you still have questions
