### ISSUE TITLE
Strategy to Send Grade Later

### ISSUE THREAD

**Issue by BTCBoss** [instructure/ims-lti#94]
Hi, 

I would like the instructor to be able to grade the work done by students on my app, before sending the grade back to the LMS. 

I thought to store the intructor lti params as a session object and create a new provider object (IMS::LTI::ToolProvider.new) when they go to grade the student's work (and create one for each students' assignment grade, just before creating it, modify the sourcedid and out service url). However, this large amount of data cannot be stored in the session (cookie overflow) and from what I have read online, it would be a bad practice to modify the session to handle the size of params. 

I also thought I could modify the provider object of the instructor like so: 

`provider.lis_result_sourcedid = "sourcedid of a particular student"
provider.lis_outcome_service_url = "outcome url of a particular student"`

But it looks like this is not possible either. What do you suggest is the best way to solve this problem? Thank you very much.

**Comment by BTCBoss** [comment]
After some digging, I found out that rather than creating a new tool provider object, I could just  create a stand-alone OutcomeRequest object like so:

```
			or_params = {
				score: 0.55,
lis_outcome_service_url:"https://canvas.instructure.com/api/lti/v1/tools/127076/grade_passback",
				lis_result_sourcedid: "127076-1053161-5383428-5567647-76991a6f2a7f51ebb390e80d3bd30b78b1903c32",
				consumer_key: config.consumer_key,
				consumer_secret: config.consumer_secret
			}

			req = IMS::LTI::OutcomeRequest.new(or_params)

# Send grade back
req.post_replace_result!(0.75)

```

This worked for me. I hope this helps anyone else out in the future and if anyone else wants to chime in on the validity of this solution, please do share.

**Comment by krozett** [comment]
Thanks for the code! I should point out that adding a `score` key to the `or_params` hash does nothing, though, as the score is a parameter in `post_replace_result!`.

**Comment by rivernate** [comment]
I'm going to close this since it's been quiet, feel free to reopen it if you still have questions
